```yaml id="q0p0mq"
version: '3.8'

services:
  telegram-news-bot:
    container_name: telegram-news-bot

    build:
      context: .
      dockerfile: Dockerfile

    restart: always

    environment:
      BOT_TOKEN: ${BOT_TOKEN}
      CHAT_ID: ${CHAT_ID}
      NEWS_API_KEY: ${NEWS_API_KEY}

    volumes:
      - .:/app

    working_dir: /app

    command: npm start
```
